version: '2.1'

services:
  postgres:
    image: postgres:14.7
    container_name: store_db
    hostname: store_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
      POSTGRES_SCHEMA: public
    volumes:
      - ./src/main/resources/db/migration/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: echo "hello"
    networks:
      - network
    restart: always

  backend:
    build: .
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - network

  frontend:
    container_name: frontend
    build: ./src/client
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - backend
    networks:
      - network

networks:
  network:
    name: network